// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    SnakeBody: typeof import('./src/components/SnakeBody.vue')['default']
    SnakeFood: typeof import('./src/components/SnakeFood.vue')['default']
  }
}
